### ISSUE TITLE
lack of documentation

### ISSUE THREAD

**Issue by ssbarnea** [andrewrothstein/ansible-anaconda#1]
At this moment this role is still using the template documentation readme file and is lacking even a minimal usage example.

Information like: for which user it would install conda, is this going to replace system python or not? ....

**Comment by andrewrothstein** [comment]
pull request?

**Comment by andrewrothstein** [comment]
Added docs. I hope it's more useful for you now. I published the updated role as v1.0.5 on the galaxy.
