### ISSUE TITLE
v4.0.1 not available on Ansible Galaxy

### ISSUE THREAD

**Issue by bretdavidson** [andrewrothstein/ansible-anaconda#18]
It looks like the latest release of this role, v4.0.1, isn't available from [Ansible Galaxy](https://galaxy.ansible.com/andrewrothstein/anaconda/).

**Comment by bretdavidson** [comment]
Sorry, just saw that this was mentioned in https://github.com/andrewrothstein/ansible-anaconda/pull/17 Thanks again for this project, feel free to close this.

**Comment by andrewrothstein** [comment]
published along with v4.0.2 to the galaxy
