### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by mochic** [andrewrothstein/ansible-anaconda#30]
hey,
would you be open to a pr to add windows support?

**Comment by andrewrothstein** [comment]
absolutely

**Comment by mochic** [comment]
- adding windows testing to travis seems complicated and time consuming for build
- would you be comfortable with me adding windows support without windows testing so long as the existing tests pass?

**Comment by andrewrothstein** [comment]
I'm fine with no CI test for Windows

**Comment by mochic** [comment]
addressed by #31
