### ISSUE TITLE
in CentOS 7 the conda binary is defined in the wrong path

### ISSUE THREAD

**Issue by besmirzanaj** [andrewrothstein/ansible-anaconda#35]
The binary for conda has a different name and path prpbably from some changes in the release archives.

The error during the update of conda is here

    TASK [andrewrothstein.anaconda : update conda pkgs...] *****************************************************************************************************************************
    Tuesday 03 December 2019  12:33:13 -0500 (0:00:00.235)       0:00:27.991 ****** 
    fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/local/anaconda/bin/conda update -y --all", "msg": "[Errno 2] No such file or directory", "rc": 2}

The new location of the installed binary is here

    /usr/local/anaconda/conda.exe

instead of here

    /usr/local/anaconda/bin/conda

**Comment by andrewrothstein** [comment]
need some more context. r u targeting windows or a linux?

**Comment by besmirzanaj** [comment]
this was running in CentOS 7.
the binary had an .exe extension, yup
*Besmir ZANAJ*

**Comment by andrewrothstein** [comment]
what version of the role are you using? what version of anaconda are you using?

**Comment by besmirzanaj** [comment]
Jut using whatever is in the role. No customizations or custom vars

**Comment by andrewrothstein** [comment]
As part of my CI, I build container images for every platform on every commit to the repo. These images were created about a month ago.

```
± |master ✓| → docker run --rm -it quay.io/andrewrothstein/ansible-anaconda:centos_7 bash -l -c 'conda --version'
conda 4.7.12
± |master ✓| → docker run --rm -it quay.io/andrewrothstein/ansible-anaconda:centos_7 bash -c '/usr/local/anaconda/bin/conda --version'
conda 4.7.12
```

I just kicked off a rebuild of the images to see if there's any funny business in the upstream distribution. I highly doubt it given that these images are checksum-ed.

https://travis-ci.org/andrewrothstein/ansible-anaconda/builds/606919420
